workflows:
  pantryscanner_testflight:
    name: PantryScanner – TestFlight
    max_build_duration: 60
    integrations:
      # 👇 This MUST match the integration name you see in Codemagic > Teams > Integrations
      app_store_connect: PantryScanner ASC Key
    environment:
      ios_signing:
        distribution_type: app-store
        bundle_identifier: com.northpadreisles.PantryScanner
      vars:
        XCODE_WORKSPACE: PantryScanner.xcworkspace
        XCODE_SCHEME: PantryScanner
    scripts:
      - name: Set up CocoaPods
        script: |
          gem install cocoapods --no-document
          pod repo update
          pod install
      - name: Xcode build (archive)
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        # 👇 Using the workflow-level integration above
        auth: integration
        submit_to_testflight: true
        # Optional: auto-assign to groups you’ve set up in App Store Connect
        beta_groups:
          - Internal Testers
