workflows:
  pantryscanner_testflight:
    name: PantryScanner - TestFlight
    max_build_duration: 60

    integrations:
      # Must match Codemagic → Teams → Integrations
      app_store_connect: PantryScannerKey      

    environment:
      ios_signing:
        # Allowed: ad_hoc | app_store | development | enterprise
        distribution_type: app_store
        bundle_identifier: com.northpadreisles.PantryScanner
        
      vars:
        # Project & scheme based on your repo/logs
        XCODE_PROJECT: PantryScanner/Pantry.xcodeproj
        XCODE_SCHEME: SimpleNews
        BUNDLE_ID: com.northpadreisles.PantryScanner        
        PROFILE_NAME: PantryScanner_AppStore_Profile         # <-- exactly as shown in Codemagic UI

    scripts:
      - name: Verify bundle identifier & team (non-blocking)
        script: |
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -showBuildSettings | tee buildsettings.txt
          BID=$(awk -F= '/PRODUCT_BUNDLE_IDENTIFIER/ {gsub(/[[:space:]]/,"",$2); print $2; exit}' buildsettings.txt || true)
          TEAM=$(awk -F= '/DEVELOPMENT_TEAM =/ {gsub(/[[:space:]]/,"",$2); print $2; exit}' buildsettings.txt || true)
          echo "Detected PRODUCT_BUNDLE_IDENTIFIER: ${BID:-<none>}"
          echo "Detected DEVELOPMENT_TEAM: ${TEAM:-<none>}"
          if [ "$BID" != "com.northpadreisles.PantryScanner" ]; then
            echo "⚠️  Bundle ID in project is '$BID'. We'll override it during archive."
          fi


      - name: Prepare signing (install certs, ensure App Store profile)
        script: |
          set -e
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA
        script: |
          echo "Project: $XCODE_PROJECT"
          echo "Scheme:  $XCODE_SCHEME"
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-xcargs "PRODUCT_BUNDLE_IDENTIFIER=com.northpadreisles.PantryScanner DEVELOPMENT_TEAM=R8R77PB278 CODE_SIGN_STYLE=Manual"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
