workflows:
  pantryscanner_testflight:
    name: PantryScanner - TestFlight
    max_build_duration: 60

    integrations:
      # Must match Codemagic → Teams → Integrations
      app_store_connect: PantryScannerKey      

    environment:
      ios_signing:
        # Allowed: ad_hoc | app_store | development | enterprise
        distribution_type: app_store
        bundle_identifier: com.northpadreisles.PantryScanner
        
      vars:
        # Project & scheme based on your repo/logs
        XCODE_PROJECT: PantryScanner/Pantry.xcodeproj
        XCODE_SCHEME: SimpleNews
        BUNDLE_ID: com.northpadreisles.PantryScanner        
        PROFILE_NAME: PantryScanner_AppStore_Profile         # <-- exactly as shown in Codemagic UI

    scripts:
      - name: Install certs & profiles
        script: |
          set -e
          keychain initialize
          keychain add-certificates
          
          # Download (or create if missing) the App Store profile for this bundle id
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          
          # Install any uploaded provisioning profiles into the local build environment
          xcode-project use-profiles

      - name: Build IPA (force matching profile + identity + bundle id)
        script: |
          xcode-project build-ipa \
            --project "PantryScanner/Pantry.xcodeproj" \
            --scheme "SimpleNews" \
            --archive-xcargs "PRODUCT_BUNDLE_IDENTIFIER=com.northpadreisles.PantryScanner DEVELOPMENT_TEAM=R8R77PB278 CODE_SIGN_STYLE=Manual PROVISIONING_PROFILE_SPECIFIER='${PROVISIONING_PROFILE_SPECIFIER}' PROVISIONING_PROFILE='${PROVISIONING_PROFILE}' CODE_SIGN_IDENTITY='Apple Distribution'"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
