workflows:
  pantryscanner_testflight:
    name: PantryScanner - TestFlight
    max_build_duration: 60

    integrations:
      # Must match Codemagic → Teams → Integrations
      app_store_connect: PantryScannerKey      

    environment:
      ios_signing:
        # Allowed: ad_hoc | app_store | development | enterprise
        distribution_type: app_store
        bundle_identifier: com.northpadreisles.PantryScanner
        
      vars:
        # Project & scheme based on your repo/logs
        XCODE_PROJECT: PantryScanner/Pantry.xcodeproj
        XCODE_SCHEME: SimpleNews
        BUNDLE_ID: com.northpadreisles.PantryScanner        
        #apple_team_id: R8R77PB278

    scripts:
      - name: Verify bundle identifier & team (non-blocking)
        script: |
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -showBuildSettings | tee buildsettings.txt
          BID=$(awk -F= '/PRODUCT_BUNDLE_IDENTIFIER/ {gsub(/[[:space:]]/,"",$2); print $2; exit}' buildsettings.txt || true)
          TEAM=$(awk -F= '/DEVELOPMENT_TEAM =/ {gsub(/[[:space:]]/,"",$2); print $2; exit}' buildsettings.txt || true)
          echo "Detected PRODUCT_BUNDLE_IDENTIFIER: ${BID:-<none>}"
          echo "Detected DEVELOPMENT_TEAM: ${TEAM:-<none>}"
          if [ "$BID" != "com.northpadreisles.PantryScanner" ]; then
            echo "⚠️  Bundle ID in project is '$BID'. We'll override it during archive."
          fi


      - name: Prepare signing (install certs, ensure App Store profile)
        script: |
          keychain initialize
          keychain add-certificates
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          xcode-project use-profiles

      - name: Ensure App Store profile & export specifier
        script: |
          set -euo pipefail
          BUNDLE_ID="com.northpadreisles.PantryScanner"
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create

          PROFILE_NAME=""
          for f in "$HOME/Library/MobileDevice/Provisioning Profiles/"*.mobileprovision; do
            [ -e "$f" ] || continue
            PLIST=$(mktemp)
            security cms -D -i "$f" > "$PLIST" 2>/dev/null || { rm -f "$PLIST"; continue; }
            APPID=$(/usr/libexec/PlistBuddy -c 'Print :Entitlements:application-identifier' "$PLIST" 2>/dev/null || echo "")
            NAME=$(/usr/libexec/PlistBuddy -c 'Print :Name' "$PLIST" 2>/dev/null || echo "")
            GETTASK=$(/usr/libexec/PlistBuddy -c 'Print :Entitlements:get-task-allow' "$PLIST" 2>/dev/null || echo "")
            rm -f "$PLIST"

            if [ "${APPID##*.}" = "$BUNDLE_ID" ] && [ "$GETTASK" = "false" ]; then
              PROFILE_NAME="$NAME"
            fi
          done

          if [ -z "$PROFILE_NAME" ]; then
            echo "❌ No App Store provisioning profile found for $BUNDLE_ID"
            exit 1
          fi

          echo "Using provisioning profile: $PROFILE_NAME"
          echo "PROVISIONING_PROFILE_SPECIFIER=$PROFILE_NAME" >> "$CM_ENV"

          keychain initialize
          keychain add-certificates
          xcode-project use-profiles


      - name: Build IPA
        script: |
          echo "Project: $XCODE_PROJECT"
          echo "Scheme:  $XCODE_SCHEME"
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-xcargs "PRODUCT_BUNDLE_IDENTIFIER=com.northpadreisles.PantryScanner DEVELOPMENT_TEAM=R8R77PB278 CODE_SIGN_STYLE=Manual"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
