workflows:
  pantryscanner_testflight:
    name: PantryScanner - TestFlight
    max_build_duration: 60

    integrations:
      # Must match Codemagic → Teams → Integrations
      app_store_connect: PantryScannerKey      

    environment:
      ios_signing:
        # Allowed: ad_hoc | app_store | development | enterprise
        distribution_type: app_store
        bundle_identifier: com.northpadreisles.PantryScanner
        
      vars:
        # Project & scheme based on your repo/logs
        XCODE_PROJECT: PantryScanner/Pantry.xcodeproj
        XCODE_SCHEME: SimpleNews
        BUNDLE_ID: com.northpadreisles.PantryScanner        
        #apple_team_id: R8R77PB278

    scripts:
      - name: Verify bundle identifier & team
        script: |
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -list
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -showBuildSettings | tee buildsettings.txt
          BID=$(awk -F= '/PRODUCT_BUNDLE_IDENTIFIER/ {gsub(/[[:space:]]/,"",$2); print $2; exit}' buildsettings.txt)
          TEAM=$(awk -F= '/DEVELOPMENT_TEAM =/ {gsub(/[[:space:]]/,"",$2); print $2; exit}' buildsettings.txt)
          echo "Detected PRODUCT_BUNDLE_IDENTIFIER: $BID"
          echo "Detected DEVELOPMENT_TEAM: $TEAM"
          test "$BID" = "$BUNDLE_ID" || { echo "❌ Bundle ID mismatch ($BID != $BUNDLE_ID)"; exit 1; }
          test "$TEAM" = "R8R77PB278" || { echo "❌ Team mismatch ($TEAM != R8R77PB278)"; exit 1; }

      - name: Prepare signing (install certs, ensure App Store profile)
        script: |
          keychain initialize
          keychain add-certificates
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          xcode-project use-profiles

      - name: Build IPA
        script: |
          echo "Project: $XCODE_PROJECT"
          echo "Scheme:  $XCODE_SCHEME"
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
